version: '3.7'
services:
  app-1:
    image: wyveo/nginx-php-fpm:php80
    volumes:
      - ./app.1:/usr/share/nginx/html
    networks:
      - app-network
  app-2:
    image: wyveo/nginx-php-fpm:php80
    volumes:
      - ./app.2:/usr/share/nginx/html
    networks:
      - app-network
  lb-1:
    build: ./nginx
    ports:
    - "8000:80"
    networks:
      - app-network

networks:
    app-network: