apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: php-fpm
  name: php-fpm
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: php-fpm
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: php-fpm
    spec:
      containers:
      - image: php-fpm
        imagePullPolicy: ""
        name: php-fpm
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
