apiVersion: skaffold/v2beta19
kind: Config
metadata:
  name: nginx-php-xdebug-skaffold
build:
  artifacts:
  - image: nginx
    docker:
      dockerfile: nginx.Dockerfile
  - image: php-fpm
    docker:
      dockerfile: php.Dockerfile
deploy:
  kubectl:
    manifests:
    - nginx-deployment.yaml
    - nginx-service.yaml
    - php-fpm-deployment.yaml
